-- Supplier Stock Mapping — LIVE query
-- Source: heroic-ruler-198603.xx_development.popeye_production_au_public_supplier_stock
-- Reproduces the curated dashboard: qty>0, exclude DELETED pids, restrict to the
-- hand-curated 31-supplier account set, and roll location-level rows up to a supplier key.
-- Returns location-level counts; sum by supplier_key for the top-level bars.
-- NOTE: unlike the original static snapshot, Chapel Corner non-tyre accessory SKUs are
--       NOT excluded here (that was a manual SKU-level list); its not-mapped count is ~1,773 higher.

WITH name_map AS (
  SELECT * FROM UNNEST([
    STRUCT('Tempetyres VIC' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres QLD' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres NSW' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres SA' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres WA' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres Special NSW' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres Special VIC' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres Special SA' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Tempetyres Special WA' AS supplier_name, 'tempetyres' AS supplier_key),
    STRUCT('Total Tyres Virtual VIC' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres Virtual NSW' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres Virtual WA' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres Virtual QLD' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres Virtual SA' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres VIC' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres WA' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres NSW' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres TOW' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres TAS' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Total Tyres SA' AS supplier_name, 'totaltyres' AS supplier_key),
    STRUCT('Yhi NSW' AS supplier_name, 'yhi' AS supplier_key),
    STRUCT('Yhi QLD' AS supplier_name, 'yhi' AS supplier_key),
    STRUCT('Yhi VIC' AS supplier_name, 'yhi' AS supplier_key),
    STRUCT('Yhi WA' AS supplier_name, 'yhi' AS supplier_key),
    STRUCT('Yhi SA' AS supplier_name, 'yhi' AS supplier_key),
    STRUCT('Yhi TAS' AS supplier_name, 'yhi' AS supplier_key),
    STRUCT('Newbee NSW Tyres Virtual' AS supplier_name, 'newbee' AS supplier_key),
    STRUCT('Newbee NSW' AS supplier_name, 'newbee' AS supplier_key),
    STRUCT('Newbee QLD Tyres' AS supplier_name, 'newbee' AS supplier_key),
    STRUCT('Newbee VIC Tyres' AS supplier_name, 'newbee' AS supplier_key),
    STRUCT('Newbee Wollongong Tyres' AS supplier_name, 'newbee' AS supplier_key),
    STRUCT('Goodride NSW Riverwood' AS supplier_name, 'goodride' AS supplier_key),
    STRUCT('Goodride' AS supplier_name, 'goodride' AS supplier_key),
    STRUCT('Goodride NSW Padstow' AS supplier_name, 'goodride' AS supplier_key),
    STRUCT('Goodride NSW Gosford' AS supplier_name, 'goodride' AS supplier_key),
    STRUCT('Goodride ACT' AS supplier_name, 'goodride' AS supplier_key),
    STRUCT('Goodride NSW Wollongong' AS supplier_name, 'goodride' AS supplier_key),
    STRUCT('Yokohama NSW' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Yokohama VIC' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Yokohama QLD Brisbane' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Yokohama WA' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Yokohama NT' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Yokohama QLD Townsville' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Yokohama SA' AS supplier_name, 'yokohama' AS supplier_key),
    STRUCT('Neta Tyres Brisbane Qld' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Neta Tyres Gold Coast Qld' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Neta Tyres Rockhampton Qld' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Neta Tyres Cairns Qld' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Neta Tyres Toowoomba Qld' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Neta Tyres Sunshine Coast Qld' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Neta Tyres Lismore Nsw' AS supplier_name, 'neta' AS supplier_key),
    STRUCT('Pirelli NSW' AS supplier_name, 'pirelli' AS supplier_key),
    STRUCT('Pirelli VIC' AS supplier_name, 'pirelli' AS supplier_key),
    STRUCT('Pirelli QLD' AS supplier_name, 'pirelli' AS supplier_key),
    STRUCT('Pirelli WA' AS supplier_name, 'pirelli' AS supplier_key),
    STRUCT('Tyre Connect' AS supplier_name, 'tyreconnect' AS supplier_key),
    STRUCT('Hankook WA' AS supplier_name, 'hankook' AS supplier_key),
    STRUCT('Hankook NSW' AS supplier_name, 'hankook' AS supplier_key),
    STRUCT('Hankook VIC' AS supplier_name, 'hankook' AS supplier_key),
    STRUCT('Hankook QLD' AS supplier_name, 'hankook' AS supplier_key),
    STRUCT('Hankook SA' AS supplier_name, 'hankook' AS supplier_key),
    STRUCT('Chapel Corner RPM' AS supplier_name, 'chapelcorner' AS supplier_key),
    STRUCT('Chapel Corner Goodyear' AS supplier_name, 'chapelcorner' AS supplier_key),
    STRUCT('Chapel Corner Virtual' AS supplier_name, 'chapelcorner' AS supplier_key),
    STRUCT('Chapel Corner Megabus' AS supplier_name, 'chapelcorner' AS supplier_key),
    STRUCT('Chapel Corner MPS' AS supplier_name, 'chapelcorner' AS supplier_key),
    STRUCT('Logic Kumho WA' AS supplier_name, 'logictyres' AS supplier_key),
    STRUCT('Logic Kumho VIC' AS supplier_name, 'logictyres' AS supplier_key),
    STRUCT('Logic Kumho QLD' AS supplier_name, 'logictyres' AS supplier_key),
    STRUCT('Logic Kumho NSW Marsden Park' AS supplier_name, 'logictyres' AS supplier_key),
    STRUCT('Logic Kumho SA' AS supplier_name, 'logictyres' AS supplier_key),
    STRUCT('Logic Tyres NSW Seven Hills' AS supplier_name, 'logictyres' AS supplier_key),
    STRUCT('Continental Tyres WA' AS supplier_name, 'continental' AS supplier_key),
    STRUCT('Continental Tyres QLD' AS supplier_name, 'continental' AS supplier_key),
    STRUCT('Continental Tyres VIC' AS supplier_name, 'continental' AS supplier_key),
    STRUCT('Continental Tyres NSW' AS supplier_name, 'continental' AS supplier_key),
    STRUCT('Toptyres QLD' AS supplier_name, 'toptyres' AS supplier_key),
    STRUCT('Toptyres NSW' AS supplier_name, 'toptyres' AS supplier_key),
    STRUCT('Toptyres TOW' AS supplier_name, 'toptyres' AS supplier_key),
    STRUCT('Toptyres SA' AS supplier_name, 'toptyres' AS supplier_key),
    STRUCT('Cypress Tyres Qld Brisbane' AS supplier_name, 'cypresstyres' AS supplier_key),
    STRUCT('Cypress Tyres Nsw' AS supplier_name, 'cypresstyres' AS supplier_key),
    STRUCT('Cypress Tyres Qld Gold Coast' AS supplier_name, 'cypresstyres' AS supplier_key),
    STRUCT('Cypress Tyres VIC Pty Ltd' AS supplier_name, 'cypresstyres' AS supplier_key),
    STRUCT('The Tyre Professionals Virtual' AS supplier_name, 'tyreprofessionals' AS supplier_key),
    STRUCT('The Tyre Professionals' AS supplier_name, 'tyreprofessionals' AS supplier_key),
    STRUCT('Freedom Tyres VIC' AS supplier_name, 'freedomtyres' AS supplier_key),
    STRUCT('Freedom Tyres QLD' AS supplier_name, 'freedomtyres' AS supplier_key),
    STRUCT('Freedom Tyres NSW' AS supplier_name, 'freedomtyres' AS supplier_key),
    STRUCT('Freedom Tyres WA' AS supplier_name, 'freedomtyres' AS supplier_key),
    STRUCT('Onyx Vic' AS supplier_name, 'onyx' AS supplier_key),
    STRUCT('Onyx Tyres Qld Brisbane' AS supplier_name, 'onyx' AS supplier_key),
    STRUCT('OLD Onyx Tyres NSW' AS supplier_name, 'onyx' AS supplier_key),
    STRUCT('OLD Onyx Tyres Qld Gold Coast' AS supplier_name, 'onyx' AS supplier_key),
    STRUCT('Onyx Qld Sunshine Coast' AS supplier_name, 'onyx' AS supplier_key),
    STRUCT('Tyregenie' AS supplier_name, 'tyregenie' AS supplier_key),
    STRUCT('St George Tyres' AS supplier_name, 'stgeorge' AS supplier_key),
    STRUCT('Tyrenetwork VIC' AS supplier_name, 'tyrenetwork' AS supplier_key),
    STRUCT('Tyrenetwork QLD' AS supplier_name, 'tyrenetwork' AS supplier_key),
    STRUCT('Tyrenetwork' AS supplier_name, 'tyrenetwork' AS supplier_key),
    STRUCT('Tyrenetwork NSW' AS supplier_name, 'tyrenetwork' AS supplier_key),
    STRUCT('Tyrenetwork SA' AS supplier_name, 'tyrenetwork' AS supplier_key),
    STRUCT('Superior Tyres' AS supplier_name, 'superior' AS supplier_key),
    STRUCT('BSA Tyres NSW' AS supplier_name, 'bsatyres' AS supplier_key),
    STRUCT('Kumho' AS supplier_name, 'kumho' AS supplier_key),
    STRUCT('Tyredepot' AS supplier_name, 'tyredepot' AS supplier_key),
    STRUCT('Tyredepot Virtual' AS supplier_name, 'tyredepot' AS supplier_key),
    STRUCT('Townsend' AS supplier_name, 'townsend' AS supplier_key),
    STRUCT('GetAGrip' AS supplier_name, 'getagrip' AS supplier_key),
    STRUCT('SPMotorcycles' AS supplier_name, 'spmotorcycles' AS supplier_key),
    STRUCT('Goodride WA' AS supplier_name, 'goodride-wa' AS supplier_key),
    STRUCT('Atlastyres' AS supplier_name, 'atlastyres' AS supplier_key),
    STRUCT('Michelin VIC' AS supplier_name, 'michelin' AS supplier_key),
    STRUCT('Michelin NSW' AS supplier_name, 'michelin' AS supplier_key),
    STRUCT('Michelin WA' AS supplier_name, 'michelin' AS supplier_key),
    STRUCT('Michelin QLD' AS supplier_name, 'michelin' AS supplier_key)
  ])
)
SELECT
  m.supplier_key,
  s.supplier_name,
  s.match_status,
  COUNT(*) AS n
FROM `heroic-ruler-198603.xx_development.popeye_production_au_public_supplier_stock` s
JOIN name_map m USING (supplier_name)
WHERE s.qty > 0
  AND s.supplier_pid NOT LIKE r"DELETED_%"
GROUP BY m.supplier_key, s.supplier_name, s.match_status
ORDER BY m.supplier_key, s.supplier_name, s.match_status
